image: gitpod/workspace-dotnet

ports:
  - port: 5000
    onOpen: ignore
  - port: 5001
    onOpen: open-preview

tasks:
  - init: 'echo "TODO: Replace with init/build command"'
    command: dotnet build Challenge
    
vscode:
  extensions:
    - ms-vscode.csharp@1.21.12:kw8SkO8+aVTSFug281WfQQ==
